chatbot:
  model: gpt-4o-mini
  temperature: 0.0
  top_p: 0.8
  max_tokens: 2000

cache:
  ttl_seconds: 3600
  length_string: 16
  max_length_string: 32

retrieval:
  embedding_model: text-embedding-3-small
  rerank_model: BAAI/bge-reranker-base
  vector_database_name_space: ns1
  vector_database_index_name: chatbot1
  use_fp16: True
  retrieval_top_k: 5
  rerank_top_k: 3
  
